name: Deploy to GitHub Pages

on:
  push:
  workflow_dispatch:

jobs:
  jekyll_build:
    runs-on: ubuntu-latest
    if: github.repository == 'illusion0001/illusion0001.github.io'
    steps:

      - name: Setup vars
        run: |
          echo patch_repo="console-game-patches" >> ${{ github.env }}
          echo ghpatch_repo="GoldHEN_Patch_Repository" >> ${{ github.env }}

      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Checkout patch repository
        uses: actions/checkout@v3
        with:
          repository: 'illusion0001/${{ env.patch_repo }}'
          path: ${{ env.patch_repo }}

      - name: Checkout patch repository
        uses: actions/checkout@v3
        with:
          repository: 'GoldHEN/${{ env.ghpatch_repo }}'
          path: ${{ env.ghpatch_repo }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Setup dependencies
        run: pip install -r ${{ env.patch_repo }}/requirements.txt

      - name: Pack patch files into zip
        run: |
          mv ${{ env.ghpatch_repo }}/patches ${{ env.patch_repo }}/patches
          cd ${{ env.patch_repo }}
          python page-autogen.py
          mv patches ../
          mv _patch0 ../
          mv _patch  ../
          cd ..
          cp -r _patch __patch
          chmod +x .ci/*.sh
          .ci/zip.sh

      - name: Deploy
        if: github.ref_name == 'main'
        uses: helaili/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
          jekyll_src: .
